name: Conda Python 3.11

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda with Python 3.11
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.11
        channels: conda-forge
        activate-environment: test-env
        environment-file: environment.yml  # optionnel si tu utilises un fichier .yml

    - name: Check Python version
      shell: bash -l {0}
      run: python --version
