name: Conda Python 3.11 with tkinter and reportlab

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: test-env

      - name: Create Conda environment with Python 3.11, tkinter, reportlab
        shell: bash -l {0}
        run: |
          conda create -n test-env python=3.11 tk reportlab -c conda-forge -y

      - name: Activate Conda env and check Python version
        shell: bash -l {0}
        run: |
          conda activate test-env
          which python
          python --version
          python -c "import tkinter; import reportlab; print('tkinter and reportlab OK')"
